@Minecraft_Realms_Emulator_HostAddress = http://localhost:8080

GET {{Minecraft_Realms_Emulator_HostAddress}}/mco/available
Accept: application/json

###

GET {{Minecraft_Realms_Emulator_HostAddress}}/mco/client/compatible
Accept: application/json

###

GET {{Minecraft_Realms_Emulator_HostAddress}}/worlds
Accept: application/json

###